---
Name: foldergallery-settings
---
Juanitou\FolderGallery:
  THUMBNAIL_IMAGE_WIDTH: 150
  THUMBNAIL_IMAGE_HEIGHT: 115
  PREVIEW_IMAGE_MAX_SIZE: 800
  ALBUMS_PER_PAGE: 16
  IMAGES_PER_PAGE: 12
  IMAGE_SORT_OPTION: 1
  IMAGE_SORT_ORDER: 1
  SHOW_BREADCRUMBS: true
GDBackend:
  default_quality: 95
SilverStripe\Assets\Image:
  extensions:
    - Juanitou\FolderGallery\FolderGalleryImageExtension
